### ISSUE TITLE
unexpected panic 

### ISSUE THREAD

**Issue by denghongcai** [parnurzeal/gorequest#66]
```bash
goroutine 598 [IO wait]:                                                                                                                                                              [46/1484]
net.runtime_pollWait(0x7ff76c32ab08, 0x77, 0x44fce0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8205cc760, 0x77, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc8205cc760, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc8205cc700, 0x0, 0x0, 0x7ff769cd20d8, 0xc82029a460, 0xecdf654be, 0x2514b38e, 0xa93e80, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc8205cc700, 0x7ff769c920e8, 0x0, 0x7ff769c920e8, 0xc82027c300, 0xecdf654be, 0x2514b38e, 0xa93e80, 0x0, 0x0)
        /usr/local/go/src/net/sock_posix.go:137 +0x351
net.socket(0x861978, 0x3, 0x2, 0x1, 0x0, 0xc82027c300, 0x7ff769c920e8, 0x0, 0x7ff769c920e8, 0xc82027c300, ...)
        /usr/local/go/src/net/sock_posix.go:89 +0x411
net.internetSocket(0x861978, 0x3, 0x7ff769c920e8, 0x0, 0x7ff769c920e8, 0xc82027c300, 0xecdf654be, 0xc82514b38e, 0xa93e80, 0x1, ...)
        /usr/local/go/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0x861978, 0x3, 0x0, 0xc82027c300, 0xecdf654be, 0xc82514b38e, 0xa93e80, 0xc82042e590, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc8200b0380, 0x7ff769c92058, 0xc82027c300, 0xecdf654be, 0x2514b38e, 0xa93e80, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0xecdf654be, 0x2514b38e, 0xa93e80, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:336 +0x75
net.dial(0x861978, 0x3, 0x7ff769c92058, 0xc82027c300, 0xc8203035e0, 0xecdf654be, 0x2514b38e, 0xa93e80, 0x0, 0x0, ...)
        /usr/local/go/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc8200b0380, 0xc82042e590, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc820303858, 0x861978, 0x3, 0xc82029a327, 0x13, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:232 +0x50f
net.DialTimeout(0x861978, 0x3, 0xc82029a327, 0x13, 0x2540be400, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:193 +0xa2
github.com/parnurzeal/gorequest.(*SuperAgent).Timeout.func1(0x861978, 0x3, 0xc82029a327, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/workspace/golang/src/github.com/parnurzeal/gorequest/main.go:337 +0x92
net/http.(*Transport).dial(0xc8202ac5a0, 0x861978, 0x3, 0xc82029a327, 0x13, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc8202ac5a0, 0xc8200b0280, 0xc82029a360, 0x4, 0xc82042e540, 0xd, 0xc8203e56e0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc8202ac5a0, 0xc8200b0280, 0xc82029a360, 0x4, 0xc82042e540, 0xd, 0xc820478480)
        /usr/local/go/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:551 +0x265
```

this panic is appeared after some request successfully done

**Comment by denghongcai** [comment]
my fault, sorry...

**Comment by denghongcai** [comment]
my fault, sorry...
