### ISSUE TITLE
On set cookie get panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Temorfeouz** [parnurzeal/gorequest#94]
Hi! I cant set cookies... Here my example:
Golang ver 1.6
```
expiration := time.Now().Add(365 * 24 * time.Hour)
cookie := http.Cookie{Name: "username", Value: "astaxie", Expires: expiration}
cookies = append(cookies, &cookie)

browser := new(BrowserStaticStruct)
browser.SetCookies(cookies)
```

Result is:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40a49a]
`

What I doing wrong?

**Comment by QuentinPerez** [comment]
Hi @Temorfeouz,

Can you give us the full trace ?

**Comment by Temorfeouz** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40a49a]

goroutine 34 [running]:
panic(0x7907c0, 0xc82000a110)
        /home/t/src/GOLANG-GOROOT/1.6/src/runtime/panic.go:464 +0x3e6
main.(*WorkerStruct).getStaticPage(0x9ffce1, 0xc82010e000, 0xc8200f0050, 0x805960, 0x0, 0x0)
        /home/t/src/go/src/serp/getter/model_worker.go:133 +0x58a
main.(*WorkerStruct).taskPage(0x9ffce1, 0xc82010e000, 0x0)
        /home/t/src/go/src/serp/getter/model_worker.go:95 +0x7da
created by main.(*WorkerStruct).addTask
        /home/t/src/go/src/serp/getter/model_worker.go:52 +0x717

```

on line model_worker.go:133 :
`browser.SetCookies(cookies)`

```
type BrowserStaticStruct struct {
	browser     *gorequest.SuperAgent
}
func (b *BrowserStaticStruct) SetCookies(cookies []*http.Cookie) {
	b.browser.AddCookies(cookies)
}
```

**Comment by QuentinPerez** [comment]
This code doesn't crash, are you sure that the issue come from gorequest ?

```console
type BrowserStaticStruct struct {
	Browser *gorequest.SuperAgent
}

func (b *BrowserStaticStruct) SetCookies(cookies []*http.Cookie) {
	b.Browser.AddCookies(cookies)
}

func main() {
	expiration := time.Now().Add(365 * 24 * time.Hour)
	cookies := []*http.Cookie{}
	cookie := http.Cookie{Name: "username", Value: "astaxie", Expires: expiration}
	cookies = append(cookies, &cookie)

	browser := new(BrowserStaticStruct)
	browser.Browser = &gorequest.SuperAgent{}
	browser.SetCookies(cookies)
}
```

**Comment by Temorfeouz** [comment]
you are right.. error somewere in my code.  I must do this check first of all))
